---
abstract: "HTML::FillInForm::Lite 'fillinform' for Text::Xslate"
author:
  - 'Yoshihiro Sasaki <ysasaki at cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Xslate-Bridge-FillInForm-Lite
no_index:
  directory:
    - t
    - inc
requires:
  HTML::FillInForm::Lite: 0
  Text::Xslate: 0
version: 0.01
